{{ $project := .Values.infrastructure }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-{{ $project.name }}
  labels:
    argocd.argoproj.io/secret-type: repository
    app.kubernetes.io/part-of: argocd
data:
  url: {{ $project.repoUrl | b64enc }}
  name: {{ printf $project.name | b64enc }}
  type: {{ printf "git" | b64enc }}
  password: {{ printf .Values.githubToken.password | b64enc }}
  username: {{ printf .Values.githubToken.name | b64enc }}