controller:
  logFormat: json
  env:
    - name: TZ
      value: Europe/Berlin
repoServer:
  logFormat: json
  env:
    - name: TZ
      value: Europe/Berlin
dex:
  env:
    - name: TZ
      value: Europe/Berlin
configs:
  secret:
    createSecret: false
server:
  service:
    type: LoadBalancer
  env:
    - name: TZ
      value: Europe/Berlin
  logFormat: json
  rbacConfig:
    policy.csv: |
      g, ADMIN, role:admin
  configEnabled: false